USE team102_2016;

latin1_swedish_ci;


insert into `match_team_pts_v`(`tournament_id`,`match_number`,`team_number`,`alliance`,`auto_reach_pts`,`auto_cross_pts`,`auto_high_goal_attempts`,`auto_high_goal_success`,`auto_high_goal_pts`,`auto_low_goal_attempts`,`auto_low_goal_success`,`auto_low_goal_pts`,`end_position_pts`,`challenge`,`scale`,`POR_Attempts`,`POR_Success`,`POR_Pts`,`CDF_Attempts`,`CDF_Success`,`CDF_Pts`,`MOT_Attempts`,`MOT_Success`,`MOT_Pts`,`RMP_Attempts`,`RMP_Success`,`RMP_Pts`,`DRW_Attempts`,`DRW_Success`,`DRW_Pts`,`SLP_Attempts`,`SLP_Success`,`SLP_Pts`,`RCK_Attempts`,`RCK_Success`,`RCK_Pts`,`RGT_Attempts`,`RGT_Success`,`RGT_Pts`,`LOB_Attempts`,`LOB_Success`,`LOB_Pts`,`LOW_Attempts`,`LOW_Success`,`LOW_Pts`,`HGH_Attempts`,`HGH_Success`,`HGH_Pts`,`Defense`) values ('MTO',1,56,'BLUE',2,0,0,0,0,0,0,0,5,1,0,0,0,0,4,3,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
insert into `match_team_pts_v`(`tournament_id`,`match_number`,`team_number`,`alliance`,`auto_reach_pts`,`auto_cross_pts`,`auto_high_goal_attempts`,`auto_high_goal_success`,`auto_high_goal_pts`,`auto_low_goal_attempts`,`auto_low_goal_success`,`auto_low_goal_pts`,`end_position_pts`,`challenge`,`scale`,`POR_Attempts`,`POR_Success`,`POR_Pts`,`CDF_Attempts`,`CDF_Success`,`CDF_Pts`,`MOT_Attempts`,`MOT_Success`,`MOT_Pts`,`RMP_Attempts`,`RMP_Success`,`RMP_Pts`,`DRW_Attempts`,`DRW_Success`,`DRW_Pts`,`SLP_Attempts`,`SLP_Success`,`SLP_Pts`,`RCK_Attempts`,`RCK_Success`,`RCK_Pts`,`RGT_Attempts`,`RGT_Success`,`RGT_Pts`,`LOB_Attempts`,`LOB_Success`,`LOB_Pts`,`LOW_Attempts`,`LOW_Success`,`LOW_Pts`,`HGH_Attempts`,`HGH_Success`,`HGH_Pts`,`Defense`) values ('MTO',1,219,'RED',2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
insert into `match_team_pts_v`(`tournament_id`,`match_number`,`team_number`,`alliance`,`auto_reach_pts`,`auto_cross_pts`,`auto_high_goal_attempts`,`auto_high_goal_success`,`auto_high_goal_pts`,`auto_low_goal_attempts`,`auto_low_goal_success`,`auto_low_goal_pts`,`end_position_pts`,`challenge`,`scale`,`POR_Attempts`,`POR_Success`,`POR_Pts`,`CDF_Attempts`,`CDF_Success`,`CDF_Pts`,`MOT_Attempts`,`MOT_Success`,`MOT_Pts`,`RMP_Attempts`,`RMP_Success`,`RMP_Pts`,`DRW_Attempts`,`DRW_Success`,`DRW_Pts`,`SLP_Attempts`,`SLP_Success`,`SLP_Pts`,`RCK_Attempts`,`RCK_Success`,`RCK_Pts`,`RGT_Attempts`,`RGT_Success`,`RGT_Pts`,`LOB_Attempts`,`LOB_Success`,`LOB_Pts`,`LOW_Attempts`,`LOW_Success`,`LOW_Pts`,`HGH_Attempts`,`HGH_Success`,`HGH_Pts`,`Defense`) values ('MTO',1,1257,'BLUE',0,10,0,0,0,1,1,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
insert into `match_team_pts_v`(`tournament_id`,`match_number`,`team_number`,`alliance`,`auto_reach_pts`,`auto_cross_pts`,`auto_high_goal_attempts`,`auto_high_goal_success`,`auto_high_goal_pts`,`auto_low_goal_attempts`,`auto_low_goal_success`,`auto_low_goal_pts`,`end_position_pts`,`challenge`,`scale`,`POR_Attempts`,`POR_Success`,`POR_Pts`,`CDF_Attempts`,`CDF_Success`,`CDF_Pts`,`MOT_Attempts`,`MOT_Success`,`MOT_Pts`,`RMP_Attempts`,`RMP_Success`,`RMP_Pts`,`DRW_Attempts`,`DRW_Success`,`DRW_Pts`,`SLP_Attempts`,`SLP_Success`,`SLP_Pts`,`RCK_Attempts`,`RCK_Success`,`RCK_Pts`,`RGT_Attempts`,`RGT_Success`,`RGT_Pts`,`LOB_Attempts`,`LOB_Success`,`LOB_Pts`,`LOW_Attempts`,`LOW_Success`,`LOW_Pts`,`HGH_Attempts`,`HGH_Success`,`HGH_Pts`,`Defense`) values ('MTO',1,4035,'BLUE',0,10,1,1,10,0,0,0,15,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
insert into `match_team_pts_v`(`tournament_id`,`match_number`,`team_number`,`alliance`,`auto_reach_pts`,`auto_cross_pts`,`auto_high_goal_attempts`,`auto_high_goal_success`,`auto_high_goal_pts`,`auto_low_goal_attempts`,`auto_low_goal_success`,`auto_low_goal_pts`,`end_position_pts`,`challenge`,`scale`,`POR_Attempts`,`POR_Success`,`POR_Pts`,`CDF_Attempts`,`CDF_Success`,`CDF_Pts`,`MOT_Attempts`,`MOT_Success`,`MOT_Pts`,`RMP_Attempts`,`RMP_Success`,`RMP_Pts`,`DRW_Attempts`,`DRW_Success`,`DRW_Pts`,`SLP_Attempts`,`SLP_Success`,`SLP_Pts`,`RCK_Attempts`,`RCK_Success`,`RCK_Pts`,`RGT_Attempts`,`RGT_Success`,`RGT_Pts`,`LOB_Attempts`,`LOB_Success`,`LOB_Pts`,`LOW_Attempts`,`LOW_Success`,`LOW_Pts`,`HGH_Attempts`,`HGH_Success`,`HGH_Pts`,`Defense`) values ('MTO',1,4285,'RED',0,0,0,0,0,0,0,0,15,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
insert into `match_team_pts_v`(`tournament_id`,`match_number`,`team_number`,`alliance`,`auto_reach_pts`,`auto_cross_pts`,`auto_high_goal_attempts`,`auto_high_goal_success`,`auto_high_goal_pts`,`auto_low_goal_attempts`,`auto_low_goal_success`,`auto_low_goal_pts`,`end_position_pts`,`challenge`,`scale`,`POR_Attempts`,`POR_Success`,`POR_Pts`,`CDF_Attempts`,`CDF_Success`,`CDF_Pts`,`MOT_Attempts`,`MOT_Success`,`MOT_Pts`,`RMP_Attempts`,`RMP_Success`,`RMP_Pts`,`DRW_Attempts`,`DRW_Success`,`DRW_Pts`,`SLP_Attempts`,`SLP_Success`,`SLP_Pts`,`RCK_Attempts`,`RCK_Success`,`RCK_Pts`,`RGT_Attempts`,`RGT_Success`,`RGT_Pts`,`LOB_Attempts`,`LOB_Success`,`LOB_Pts`,`LOW_Attempts`,`LOW_Success`,`LOW_Pts`,`HGH_Attempts`,`HGH_Success`,`HGH_Pts`,`Defense`) values ('MTO',1,4573,'RED',0,10,1,0,0,0,0,0,15,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
