USE team102_2016;

CREATE TABLE `matches` (
  `tournament_id` varchar(20) NOT NULL,
  `match_number` int(11) NOT NULL,
  `start_time` varchar(20) DEFAULT NULL,
  `red_score` int(11) DEFAULT NULL,
  `blue_score` int(11) DEFAULT NULL,
  `ignore_match` varchar(1) NOT NULL DEFAULT 'N',
  `red_breach` varchar(1) NOT NULL DEFAULT 'N',
  `blue_breach` varchar(1) NOT NULL DEFAULT 'N',
  `red_capture` varchar(1) NOT NULL DEFAULT 'N',
  `blue_capture` varchar(1) NOT NULL DEFAULT 'N',
  `red_spy_human` varchar(1) NOT NULL DEFAULT 'N',
  `blue_spy_human` varchar(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`tournament_id`,`match_number`),
  CONSTRAINT `match_tour_id` FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',1,'Sat 3/5 - 11:00 AM',43,56,'N','Y','Y','Y','Y','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',2,'Sat 3/5 - 11:07 AM',50,57,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',3,'Sat 3/5 - 11:14 AM',25,69,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',4,'Sat 3/5 - 11:24 AM',82,67,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',5,'Sat 3/5 - 11:31 AM',40,64,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',6,'Sat 3/5 - 11:38 AM',45,61,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',7,'Sat 3/5 - 11:45 AM',41,99,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',8,'Sat 3/5 - 11:52 AM',80,44,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',9,'Sat 3/5 - 11:59 AM',5,82,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',10,'Sat 3/5 - 12:09 PM',37,69,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',11,'Sat 3/5 - 12:16 PM',0,55,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',12,'Sat 3/5 - 12:23 PM',89,44,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',13,'Sat 3/5 - 12:30 PM',67,49,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',14,'Sat 3/5 - 12:37 PM',95,25,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',15,'Sat 3/5 - 12:44 PM',60,71,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',16,'Sat 3/5 - 12:54 PM',60,45,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',17,'Sat 3/5 - 1:01 PM',79,71,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',18,'Sat 3/5 - 2:08 PM',65,50,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',19,'Sat 3/5 - 2:15 PM',28,74,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',20,'Sat 3/5 - 2:22 PM',72,55,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',21,'Sat 3/5 - 2:29 PM',64,78,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',22,'Sat 3/5 - 2:39 PM',62,81,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',23,'Sat 3/5 - 2:46 PM',70,22,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',24,'Sat 3/5 - 2:53 PM',69,56,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',25,'Sat 3/5 - 3:00 PM',59,34,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',26,'Sat 3/5 - 3:07 PM',27,52,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',27,'Sat 3/5 - 3:14 PM',55,74,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',28,'Sat 3/5 - 3:24 PM',101,50,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',29,'Sat 3/5 - 3:31 PM',69,52,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',30,'Sat 3/5 - 3:38 PM',61,64,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',31,'Sat 3/5 - 3:45 PM',66,54,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',32,'Sat 3/5 - 3:52 PM',60,51,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',33,'Sat 3/5 - 3:59 PM',36,67,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',34,'Sat 3/5 - 4:09 PM',34,60,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',35,'Sat 3/5 - 4:16 PM',95,50,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',36,'Sat 3/5 - 4:23 PM',70,10,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',37,'Sat 3/5 - 4:30 PM',42,70,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',38,'Sat 3/5 - 4:37 PM',58,140,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',39,'Sat 3/5 - 4:44 PM',64,55,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',40,'Sat 3/5 - 4:54 PM',85,60,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',41,'Sat 3/5 - 5:01 PM',57,66,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',42,'Sat 3/5 - 5:08 PM',76,45,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',43,'Sat 3/5 - 5:15 PM',100,79,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',44,'Sat 3/5 - 5:22 PM',55,102,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',45,'Sat 3/5 - 5:29 PM',75,64,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',46,'Sat 3/5 - 5:39 PM',97,37,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',47,'Sat 3/5 - 5:46 PM',87,55,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',48,'Sat 3/5 - 5:53 PM',109,55,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',49,'Sat 3/5 - 6:00 PM',50,88,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',50,'Sat 3/5 - 6:07 PM',50,67,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',51,'Sat 3/5 - 6:14 PM',64,86,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',52,'Sat 3/5 - 6:24 PM',64,65,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',53,'Sat 3/5 - 6:31 PM',72,87,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',54,'Sat 3/5 - 6:38 PM',74,94,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',55,'Sun 3/6 - 9:30 AM',47,72,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',56,'Sun 3/6 - 9:37 AM',88,72,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',57,'Sun 3/6 - 9:44 AM',94,67,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',58,'Sun 3/6 - 9:54 AM',47,71,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',59,'Sun 3/6 - 10:01 AM',64,102,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',60,'Sun 3/6 - 10:08 AM',77,67,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',61,'Sun 3/6 - 10:15 AM',27,55,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',62,'Sun 3/6 - 10:22 AM',64,108,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',63,'Sun 3/6 - 10:29 AM',69,77,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',64,'Sun 3/6 - 10:39 AM',79,65,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',65,'Sun 3/6 - 10:46 AM',78,73,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',66,'Sun 3/6 - 10:53 AM',75,42,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',67,'Sun 3/6 - 11:00 AM',63,79,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',68,'Sun 3/6 - 11:07 AM',69,100,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',69,'Sun 3/6 - 11:14 AM',66,74,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',70,'Sun 3/6 - 11:24 AM',79,81,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',71,'Sun 3/6 - 11:31 AM',55,59,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',72,'Sun 3/6 - 11:38 AM',67,87,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',73,'Sun 3/6 - 11:45 AM',65,40,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',74,'Sun 3/6 - 11:52 AM',80,52,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',75,'Sun 3/6 - 11:59 AM',104,86,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',76,'Sun 3/6 - 12:06 PM',82,27,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',77,'Sun 3/6 - 12:13 PM',65,71,'N','N','N','N','N','N','N');
insert into `matches`(`tournament_id`,`match_number`,`start_time`,`red_score`,`blue_score`,`ignore_match`,`red_breach`,`blue_breach`,`red_capture`,`blue_capture`,`red_spy_human`,`blue_spy_human`) values ('MTO',78,'Sun 3/6 - 12:20 PM',81,98,'N','N','N','N','N','N','N');
