USE team102_2016;

;


insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1,'The Juggernauts',null,'Pontiac','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (11,'Mt. Olive High School','MORT','Flanders','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (25,'North Brunswick Twp. High School',null,'North Brunswick','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (27,'Team RUSH',null,'Clarkson','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (41,'Watchung Hills Regional High School','RoboWarriors','Warren','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (45,'TechnoKats Robotics team','{null}','Kokomo','IN');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (56,'Bound Brook High School','R.O.B.B.E.','Bound Brook','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (75,'Hillsborough High School','RoboRaiders','Hillsborough','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (78,'Aquidneck Island',null,'Newport','RI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (87,'Red Devils','Red Devils','Mount Holly','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (88,'Bridgewater Raynham Reg',null,'Bridgewater','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (97,'Cambridge Rindge and Latin',null,'Cambridge','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (102,'Somerville High School','The Gearheads','Somerville','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (103,'Cybersonics',null,'Kintnersville','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (111,'WildStang','','Schaumburg','IL');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (121,'Middletown High School',null,'Newport County','RI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (125,'Boston Latin & Brookline High & Revere High',null,'Boston','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (136,'Plainfield High','Killer Kardinals','Plainfield','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (155,'Berlin High School',null,'Berlin','CT');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (190,'Gompei and the H.E.R.D.',null,'Worcester','tts');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (191,'X-CATS',null,'Rochester','NY');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (193,'Mt. Olive High School 2','MORT Beta','Flanders','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (203,'Camden County Technical  School',null,'Sicklerville','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (204,'Eastern Robotic Vikings','Eastern Robotic Vikings','Voorhees','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (219,'Warren Hills Regional High School','Team Impact','Washington','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (222,'Tunkhannock Area High School','Tigertrons','Tunkhannock','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (223,'Lakeland Regional High School','Xtreme Heat','Wanaque','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (224,'Piscataway High School','The Tribe','Piscataway','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (225,'York High School',null,'York','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (230,'Shelton High School',null,'Shelton','CT');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (237,'Black Magic Robotics','','Watertown','CT');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (245,'Adambots','','Rochester Hills','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (246,'Boston University Academy',null,'Boston','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (265,'Lakeland Regional High School 2',null,'Wanaque','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (272,'Lansdale Catholic High School',null,'Lansdale','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (293,'Hopewell Valley Central High School',null,'Pennington','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (303,'Bridgewater-Raritan Regional High School','The T.E.S.T. Team','Bridgewater','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (304,'George Washington High School',null,'Philadelphia','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (316,'Cumberland County High Schools','LuNaTeCs','Carneys Point','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (330,'The Beach Bots',null,'Hermosa Beach','CA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (341,'Wissahickon High School',null,'Ambler','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (357,'Upper Darby High School',null,'Drexel Hill','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (365,'MOE','Miracle Workerz','Wilmington','DE');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (384,'Sparky 384','','Richmond','VA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (433,'Mount St. Joseph Academy','Firebirds','Flourtown','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (484,'Haverford High School',null,'Havertown','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (486,'Strath Haven High School',null,'Wallingford','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (492,'Titan Robotics','','Bellvue','VA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (494,'Goodrich High School',null,'Goodrich','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (525,'Cedar Falls High School',null,'Cedar Falls','IA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (555,'Montclair High School','Montclair Robotics','Montclair','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (568,'Diamond / East / Bartlett High Schools',null,'Anchorage','AK');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (597,'Foshay LRN Center','','Los Angeles','CA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (604,'Leland High',null,'San Jose, CA','CA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (613,'Franklin High School','NeoWarriors','Somerset','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (708,'Hatboro-Horsham High School',null,'Horsham','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (709,'Agnes Irwin School',null,'Bryn Mawr','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (714,'Technology High School','panthera','Newark','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (744,'Westminster Adademy',null,'Ft. Lauderdale','FL');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (752,'Science Park High School','The Chargers','Newark','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (816,'Anomaly','Anomaly','Westampton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (834,'Southern Lehigh SHS',null,'Center Valley','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (862,'Salem & Plymouth High Schools',null,'Canton','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (869,'Middlesex High School','PowerCord','Middlesex','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (876,'Northwood & Hatton High Schools',null,'Northwood and Hatton,','MD');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (896,'Central High School and Newark Public Schools',null,'Newark','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (967,'Linn-Mar High School',null,'Marion','IA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1002,'Wheeler High school',null,'Marietta','GA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1011,'sonoran Science Adademy - Tucson','','Tucson, AZ','AZ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1027,'West Springfield High',null,'West Springfield','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1089,'Hightstown High School','Team Mercury','Hightstown','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1124,'Avon High School',null,'Avon','CT');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1143,'Abington Heights High School','Cruzin'' Comets','Clarks Summit','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1168,'Malvern Prep School',null,'Malvern','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1189,'Grosse Pointe North HS','The Gearheadsi','Grosse Pointe','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1218,'Springside Chestnut Hill Academy',null,'Philadelphia','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1228,'Rahway High School','RoboTribe','Rahway','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1257,'Union County Vocational Technical Schools','Parallel Universe','Scotch Plains','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1279,'Immaculata High School','Cold Fusion','Somerville','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1302,'Pope John XXIII Regional High School',null,'Sparta','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1350,'La Salle Academy',null,'Providence','RI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1370,'Appoquinimink High School & Middletown High School',null,'Middletown','DE');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1403,'Montgomery High School','Cougar Robotics','Skillman','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1477,'College Park HS',null,'The Woodlands','TX');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1495,'Avon Grove High School',null,'West Grove','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1519,'Milford Area Youth Homeschoolers',null,'Milford','NH');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1540,'Caitlin Gabel School',null,'Portland','OR');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1547,'Trafalgar Castle School',null,'Whitby','ON');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1595,'St. George''s School','','Spokane','WA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1619,'Longmont High School',null,'Longmont','CO');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1626,'St. Joseph''s High School','Falcon Robotics','Metuchen','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1640,'Downingtown Area Robotics','Sab-BOT-age','Downingtown/Exton','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1647,'Iron Devils Robotics Team from Seneca and Shawnee High Schools','Iron Devils','Tabernacle','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1649,'Windmere Preparatory School',null,'Windemere','FL');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1672,'Mahwah High School Board of Education','Robo-T-Birds','Mahwah','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1676,'Pascack Valley Regional High School District','The Pascack PI-oneers','Montvale','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1690,'Ort Binyamina',null,'Binyamina','z, Israel');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1712,'Lower Merion High School',null,'Ardmore','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1726,'Buena High School',null,'sierra vista','AZ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1777,'Shawnee Mission west High',null,'Overland Park','KS');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1791,'T.O.P. Hatters','T.O.P. Hatters','Clayton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1807,'Redbird Robotics',null,'Allentown','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1811,'East Side High School','FRESH','Newark','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1902,'Orange County 4-H, Florida',null,'Orlando','FL');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1923,'West Windsor-Plainsboro HS North & South','The MidKnight Inventors','Plainsboro','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (1989,'Vernon Township High School','Viking Robotics','Vernon Township','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2016,'Ewing High & New Jersey School for the Deaf','Mighty Monkey Wrenches','Ewing','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2052,'Irondale Senior High','','New Brighton','MN');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2056,'Orchard Park Secondary School',null,'Stoney Creek, ON',null);
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2067,'New Haven County 4H',null,'Guilford, CT',null);
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2070,'Ridgefield Memorial High School','Royals','Ridgefield','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2079,'Alarm Robotics',null,'Franklin','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2168,'Fitch Senior High School',null,'Groton','CT');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2180,'Hamilton High School East','Zero Gravity','Hamilton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2191,'Nottingham High School','Flux Core','Hamilton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2375,'Phoenix Union Bio High Schoool',null,'Phoenix','AZ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2423,'Watertown High',null,'Watertown','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2451,'Neighborhood Group',null,'Saint Charles','IL');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2458,'Gill St. Bernards High School','Team Chaos','Gladstone','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2495,'Hamilton High School West','Hive Mind','Hamilton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2502,'Eden Prairie High',null,'Eden Prarie','MN');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2539,'Palmyra Area High School',null,'Palmyra','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2554,'John P Stevens High School','The WarHawks','Edison','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2559,'Dauphin County Technical High School',null,'Harrisburg','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2577,'The Pingry School','Pingry Robotics','Basking Ridge','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2590,'Robbinsville High School','Nemesis','Robbinsville','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2600,'JeffersonTwsp. High School','Team Falcon','Oak Ridge','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2607,'Archbishop Wood High School',null,'Warminster','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2626,'Seminaire de Sherbrooke',null,'Sherbrooke','QC, Canada');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2729,'Cherokee High School','Storm Robotics Team','Marlton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2836,'Nonnewaug High School','Woodbury','Woodbury','CT');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2877,'Newtown North and South High',null,'Newtown','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (2990,'Hotwire Robotics','','Aumsville','OR');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3026,'Delano Senior High',null,'Delano','MN');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3142,'Newton High School','Aperture','Newton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3146,'Granby Memorial HS',null,'Granby','CT');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3151,'Cyberstorm','Cyberstorm','Sewell','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3167,'Father Judge High School','Mechanical Misfits','Philadelphia','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3175,'University Liggett School',null,'Grosse Pointe Woods','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3236,'Tri-Country Regional',null,'Franklin','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3288,'Big Piney High School',null,'Big Piney','WY');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3314,'Clifton High School','Mechanical Mustangs','Clifton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3337,'Woodlawn HS',null,'Baton rouge','LA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3340,'Union City High School','UCHS MagneGeeks','Union City','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3397,'University City Sr High',null,'University City','MO');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3410,'Terrra environmental Research Institute',null,'Miami','FL');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3492,'Lots of high schools',null,'Windielf','WV');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3515,'John F Kennedy Memorial H. S.','Pneubotic Mustangs ','Iselin','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3562,'Bannock County 4H',null,'Pocatello','ID');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3607,'South Hunterdon Regional High School',null,'Lambertville','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3618,'Petoskey',null,'Petoskey','Id');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3637,'Hunterdon Central Regional High School','The Daleks','Flemington','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3668,'Whitmore Lake HS','','Whitmore Lake','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3674,'Battle Ground 4H',null,'Battle Ground','WA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3770,'Bullock Greek HS',null,'Midland','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3780,'Wheeler School',null,'Providence','RI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3787,'Grays Harbor 4H',null,'Westport','WA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3929,'J.R. Masterman Laboratory and Demonstration High School',null,'Philadelphia','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3944,'Tempe Preparatory Adademy',null,'Tempe','AZ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3958,'Boston College High School',null,'Boston','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (3974,'Bishop McDevitt High School','E=mCD','Wyncote','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4035,'Orange High School','Torbotix','Orange','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4128,'Holmdel High School',null,'Holmdel','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4198,'Waconia Sr. High',null,'Waconia','MN');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4281,'The Center School','BULL DOGS','Branchburg','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4285,'Honesdale High School & Western Wayne High School','Camo-Bots','Honesdale','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4311,'Swampscott High',null,'Swampscott','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4361,'Roxbury High School','Roxbotix','Succasunna','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4373,'Abington Friends School',null,'Jenkintown','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4454,'Science Leadership Academy',null,'Philadelphia','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4475,'West Market Street Center','Terrier Byte Bots','Newark','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4573,'South River High School','SRNJRambotics','South River','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4575,'The Tin Mints','The Tin Mints','Broomall','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4637,'St. Hubert Catholic High School for Girls',null,'Philadelphia','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4650,'Newark Vocational High School',null,'Newark','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4653,'Don Bosco Prep','Ironmen Robotics','Ramsey','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4719,'Sir winston Churchill','Calgary','Calgary','AB, Canada');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4750,'BERT','BERT','Pennsauken','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4796,'Academy of the Pacific Rim',null,'Hyde Park','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4908,'Duxbury High',null,'Duxbury','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4920,'Belle River HS',null,'Belle River','ON');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4954,'Middletown High School','Palindrome Robotics','Middletown','DE');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (4961,'Almont HS','','Almont','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5080,'Dickinson High School',null,'Wilmington','DE');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5112,'Ponaganset High School',null,'North Scituate','RI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5113,'Moorestown High School','Combustible Lemons','Moorestown','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5114,'Fenton Sr HS',null,'Fenton','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5181,'La Salle College High School',null,'Wyndmoor','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5216,'Garber HS',null,'Essexville','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5310,'East Orange STEM  Academy','Eagles Apex','East Orange','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5401,'Bensalem Twp High School',null,'Bensalem','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5404,'North Penn SHS',null,'Lansdale','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5407,'Aim Academy',null,'Conshohocken','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5420,'Velocity','Velocity','Bridgeton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5421,'Birch Wathen Lenox',null,'NYC','NY');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5429,'Sierra Vista HS',null,'Las Vegas','NV');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5438,'Technological Terrors','Technological Terrors','Jersey City','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5457,'Falcobots','Falcobots','Burlington','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5460,'Zemmer Junior HS',null,'Lapeer','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5490,'Moravian Academy',null,'Bethlehem','PA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5498,'Grosse Ile HS',null,'Grosse Ile','MI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5541,'Shakopee Sr High',null,'Shakopee','MN');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5554,'ort yad labovich',null,'Natanya','M, Israel');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5584,'Neighborhood Group',null,'Beronia','VIC, Austr');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5624,'South Plainfield High','Tiger Tech ','South Plainfield','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5666,'Purple Lightning','Purple Lightning','Trenton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5684,'Iron Mechs','Iron Mechs','Hamilton','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5725,'Whitney Canada - Lethbridge & Chinook HS',null,'Lethbridge','AB, canada');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5732,'Bloomfield High',' ROBOTIGERS','Bloomfield','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5735,'Neighborhood Group',null,'Wayland','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5738,'Central Falls High School',null,'Central Falls','RI');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5752,'Beverly High School',null,'Beverly','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5766,'ET Robotics',null,'Hawthorn','MA');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5895,'Peddie School Robotics',null,'Hightstown','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5938,'Razor Steel Robotics','Razor Steel Robotics','Dover','DE');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (5992,'Pirates',null,'West Orange','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (6015,'Juicy Bots',null,'Hackensack','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (6016,'Tiger Robotics',null,'Hackettstown','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (6203,'Titanium Knights Robotics','Titanium Knights Robotics','Hackensack','NJ');
insert into `teams`(`number`,`name`,`nickname`,`city`,`state`) values (6226,'Blue Devils','Blue Devils','Burlington','NJ');
