USE team102_2016;

latin1_swedish_ci;


insert into `team_avg_pts_norank_v`(`tournament_id`,`team_number`,`num_matches`,`avg_pts`,`avg_auto_def_pts`,`auto_high_att`,`auto_high_%`,`auto_lo_att`,`auto_lo_%`,`challng_%`,`scale_%`,`brch_%`,`captr_%`,`POR_Att`,`POR_%`,`CDF_Att`,`CDF_%`,`MOT_Att`,`MOT_%`,`RMP_Att`,`RMP_%`,`DRW_Att`,`DRW_%`,`SLP_Att`,`SLP_%`,`RCK_Att`,`RCK_%`,`RGT_Att`,`RGT_%`,`LOB_Att`,`LOB_%`,`LOW_Att`,`LOW_%`,`HGH_Att`,`HGH_%`,`Defense`) values ('MTO',56,1,17.0,2.0,0,null,0,null,100,0,100,100,0,null,4,75,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0);
insert into `team_avg_pts_norank_v`(`tournament_id`,`team_number`,`num_matches`,`avg_pts`,`avg_auto_def_pts`,`auto_high_att`,`auto_high_%`,`auto_lo_att`,`auto_lo_%`,`challng_%`,`scale_%`,`brch_%`,`captr_%`,`POR_Att`,`POR_%`,`CDF_Att`,`CDF_%`,`MOT_Att`,`MOT_%`,`RMP_Att`,`RMP_%`,`DRW_Att`,`DRW_%`,`SLP_Att`,`SLP_%`,`RCK_Att`,`RCK_%`,`RGT_Att`,`RGT_%`,`LOB_Att`,`LOB_%`,`LOW_Att`,`LOW_%`,`HGH_Att`,`HGH_%`,`Defense`) values ('MTO',219,1,2.0,2.0,0,null,0,null,0,0,100,100,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0);
insert into `team_avg_pts_norank_v`(`tournament_id`,`team_number`,`num_matches`,`avg_pts`,`avg_auto_def_pts`,`auto_high_att`,`auto_high_%`,`auto_lo_att`,`auto_lo_%`,`challng_%`,`scale_%`,`brch_%`,`captr_%`,`POR_Att`,`POR_%`,`CDF_Att`,`CDF_%`,`MOT_Att`,`MOT_%`,`RMP_Att`,`RMP_%`,`DRW_Att`,`DRW_%`,`SLP_Att`,`SLP_%`,`RCK_Att`,`RCK_%`,`RGT_Att`,`RGT_%`,`LOB_Att`,`LOB_%`,`LOW_Att`,`LOW_%`,`HGH_Att`,`HGH_%`,`Defense`) values ('MTO',1257,1,15.0,10.0,0,null,1,100,0,0,100,100,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0);
insert into `team_avg_pts_norank_v`(`tournament_id`,`team_number`,`num_matches`,`avg_pts`,`avg_auto_def_pts`,`auto_high_att`,`auto_high_%`,`auto_lo_att`,`auto_lo_%`,`challng_%`,`scale_%`,`brch_%`,`captr_%`,`POR_Att`,`POR_%`,`CDF_Att`,`CDF_%`,`MOT_Att`,`MOT_%`,`RMP_Att`,`RMP_%`,`DRW_Att`,`DRW_%`,`SLP_Att`,`SLP_%`,`RCK_Att`,`RCK_%`,`RGT_Att`,`RGT_%`,`LOB_Att`,`LOB_%`,`LOW_Att`,`LOW_%`,`HGH_Att`,`HGH_%`,`Defense`) values ('MTO',4035,1,35.0,10.0,1,100,0,null,100,100,100,100,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0);
insert into `team_avg_pts_norank_v`(`tournament_id`,`team_number`,`num_matches`,`avg_pts`,`avg_auto_def_pts`,`auto_high_att`,`auto_high_%`,`auto_lo_att`,`auto_lo_%`,`challng_%`,`scale_%`,`brch_%`,`captr_%`,`POR_Att`,`POR_%`,`CDF_Att`,`CDF_%`,`MOT_Att`,`MOT_%`,`RMP_Att`,`RMP_%`,`DRW_Att`,`DRW_%`,`SLP_Att`,`SLP_%`,`RCK_Att`,`RCK_%`,`RGT_Att`,`RGT_%`,`LOB_Att`,`LOB_%`,`LOW_Att`,`LOW_%`,`HGH_Att`,`HGH_%`,`Defense`) values ('MTO',4285,1,15.0,0.0,0,null,0,null,100,100,100,100,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0);
insert into `team_avg_pts_norank_v`(`tournament_id`,`team_number`,`num_matches`,`avg_pts`,`avg_auto_def_pts`,`auto_high_att`,`auto_high_%`,`auto_lo_att`,`auto_lo_%`,`challng_%`,`scale_%`,`brch_%`,`captr_%`,`POR_Att`,`POR_%`,`CDF_Att`,`CDF_%`,`MOT_Att`,`MOT_%`,`RMP_Att`,`RMP_%`,`DRW_Att`,`DRW_%`,`SLP_Att`,`SLP_%`,`RCK_Att`,`RCK_%`,`RGT_Att`,`RGT_%`,`LOB_Att`,`LOB_%`,`LOW_Att`,`LOW_%`,`HGH_Att`,`HGH_%`,`Defense`) values ('MTO',4573,1,25.0,10.0,1,0,0,null,100,100,100,100,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0,null,0);
